### PR TITLE
[CI] Add wartremover and pre-commit hook

### PR DESCRIPTION
**Pull request by mohe2015**
#3

### CODE REVIEW

**Comment by Oshgnacknak** [comment]
Getting the following error
```
[error] node:internal/crypto/hash:71
[error]   this[kHandle] = new _Hash(algorithm, xofLen);
[error]                   ^
[error] Error: error:0308010C:digital envelope routines::unsupported
[error]     at new Hash (node:internal/crypto/hash:71:19)
[error]     at Object.createHash (node:crypto:140:10)
[error]     at module.exports (/home/osh/Programming/scala/reform/webapp/target/scala-2.13/scalajs-bundler/test/node_modules/webpack/lib/util/createHash.js:135:53)
[error]     at NormalModule._initBuildHash (/home/osh/Programming/scala/reform/webapp/target/scala-2.13/scalajs-bundler/test/node_modules/webpack/lib/NormalModule.js:417:16)
[error]     at handleParseError (/home/osh/Programming/scala/reform/webapp/target/scala-2.13/scalajs-bundler/test/node_modules/webpack/lib/NormalModule.js:471:10)
[error]     at /home/osh/Programming/scala/reform/webapp/target/scala-2.13/scalajs-bundler/test/node_modules/webpack/lib/NormalModule.js:503:5
[error]     at /home/osh/Programming/scala/reform/webapp/target/scala-2.13/scalajs-bundler/test/node_modules/webpack/lib/NormalModule.js:358:12
[error]     at /home/osh/Programming/scala/reform/webapp/target/scala-2.13/scalajs-bundler/test/node_modules/loader-runner/lib/LoaderRunner.js:373:3
[error]     at iterateNormalLoaders (/home/osh/Programming/scala/reform/webapp/target/scala-2.13/scalajs-bundler/test/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
[error]     at Array.<anonymous> (/home/osh/Programming/scala/reform/webapp/target/scala-2.13/scalajs-bundler/test/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
[error]     at Storage.finished (/home/osh/Programming/scala/reform/webapp/target/scala-2.13/scalajs-bundler/test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
[error]     at /home/osh/Programming/scala/reform/webapp/target/scala-2.13/scalajs-bundler/test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
[error]     at /home/osh/Programming/scala/reform/webapp/target/scala-2.13/scalajs-bundler/test/node_modules/graceful-fs/graceful-fs.js:123:16
[error]     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
[error]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[error]   library: 'digital envelope routines',
[error]   reason: 'unsupported',
[error]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[error] }
[error] Node.js v19.0.1
[error] Failure on parsing the output of webpack: No content to map due to end-of-input
[error]  at [Source: java.lang.ProcessImpl$ProcessPipeInputStream@e3004e2; line: 1, column: 0]
[error] You can try to manually execute the command
[error] node /home/osh/Programming/scala/reform/webapp/target/scala-2.13/scalajs-bundler/test/node_modules/webpack/bin/webpack --bail --profile --json --mode development /home/osh/Programming/scala/reform/webapp/target/scala-2.13/scalajs-bundler/test/webapp-test-fastopt-loader.js --output /home/osh/Programming/scala/reform/webapp/target/scala-2.13/scalajs-bundler/test/webapp-test-fastopt-bundle.js
[error]
[error] stack trace is suppressed; run 'last webapp / Test / jsEnvInput' for the full output
[error] Total time: 2 s, completed Nov 16, 2022, 11:48:16 AM
[error] (webapp / Test / jsEnvInput) Non-zero exit code: 1
```
Using
```
$ node --version
v19.0.1
$ yarn --version
1.22.19
```

**Comment by mohe2015** [comment]
@Oshgnacknak 
> Getting the following error
> [...]
> [error]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
> [...]
> Using
> 
> ```
> $ node --version
> v19.0.1
> $ yarn --version
> 1.22.19
> ```
This should be unrelated to this pull request. I added to the documentation here though that you need nodejs 16 because our frontend framework is using an outdated version of webpack which depends on legacy openssl features. Note that the arch linux version didn't work for me and I ended up using nvm.
Alternatively you can use `export NODE_OPTIONS=--openssl-legacy-provider`

**Comment by Oshgnacknak** [comment]
Errors now being fixed I still minor complains about the noisiness of the hook.
Removing the `-x` flag from the repo version seems like a valid option to me.

**Review by Oshgnacknak — APPROVED** [review]
lgtm

**Pull request merged**
